/** Generated by scripts/generate-performance-metrics.mjs — do not edit manually. */
export type ComponentPerformanceMetric = {
  slug: string;
  rawKb: number;
  gzipKb: number;
  treeShakable: boolean;
  ssr: boolean;
};

export const componentPerformanceMetrics: ComponentPerformanceMetric[] = [
  {
    "slug": "accordion",
    "rawKb": 8.62,
    "gzipKb": 2.36,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "ai-chat",
    "rawKb": 17,
    "gzipKb": 4.67,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "ai-data-analyst",
    "rawKb": 27.26,
    "gzipKb": 7.01,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "ai-form-filler",
    "rawKb": 18.74,
    "gzipKb": 5.3,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "ai-orchestrator",
    "rawKb": 61.33,
    "gzipKb": 13.63,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "ai-search",
    "rawKb": 18.91,
    "gzipKb": 5.3,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "ai-summarizer",
    "rawKb": 18.17,
    "gzipKb": 5.12,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "ai-workflow-builder",
    "rawKb": 103.2,
    "gzipKb": 22.3,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "aspect-ratio",
    "rawKb": 0.91,
    "gzipKb": 0.44,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "auth",
    "rawKb": 20.72,
    "gzipKb": 5.92,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "badge",
    "rawKb": 0.82,
    "gzipKb": 0.43,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "breadcrumb",
    "rawKb": 5.14,
    "gzipKb": 1.5,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "button",
    "rawKb": 9.86,
    "gzipKb": 2.95,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "calendar",
    "rawKb": 16.6,
    "gzipKb": 4.11,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "callout",
    "rawKb": 6.59,
    "gzipKb": 2.05,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "card",
    "rawKb": 8.04,
    "gzipKb": 2.28,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "card-validation",
    "rawKb": 21.25,
    "gzipKb": 5.45,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "checkbox",
    "rawKb": 3.06,
    "gzipKb": 1.08,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "checkbox-card",
    "rawKb": 7.82,
    "gzipKb": 2.29,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "code-block",
    "rawKb": 4.89,
    "gzipKb": 1.74,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "color-palette",
    "rawKb": 3.96,
    "gzipKb": 1.26,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "data-grid",
    "rawKb": 79.82,
    "gzipKb": 17.79,
    "treeShakable": true,
    "ssr": false
  },
  {
    "slug": "date-picker",
    "rawKb": 25.82,
    "gzipKb": 6.06,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "dialog",
    "rawKb": 10.17,
    "gzipKb": 2.78,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "dropdown",
    "rawKb": 28.35,
    "gzipKb": 6.68,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "error-boundary",
    "rawKb": 15.84,
    "gzipKb": 4.68,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "flow-chart",
    "rawKb": 5.58,
    "gzipKb": 1.99,
    "treeShakable": true,
    "ssr": false
  },
  {
    "slug": "form",
    "rawKb": 45.84,
    "gzipKb": 11.08,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "grid",
    "rawKb": 6.99,
    "gzipKb": 2.23,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "icon",
    "rawKb": 6.19,
    "gzipKb": 2.03,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "image",
    "rawKb": 10.11,
    "gzipKb": 2.91,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "input",
    "rawKb": 8.27,
    "gzipKb": 2.4,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "label",
    "rawKb": 0.82,
    "gzipKb": 0.43,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "link",
    "rawKb": 4.39,
    "gzipKb": 1.52,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "list-item",
    "rawKb": 8.91,
    "gzipKb": 2.43,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "loader",
    "rawKb": 1.97,
    "gzipKb": 0.72,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "markdown",
    "rawKb": 19.9,
    "gzipKb": 4.76,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "menu",
    "rawKb": 13.21,
    "gzipKb": 3.57,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "metric",
    "rawKb": 11.84,
    "gzipKb": 3.04,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "monaco-editor",
    "rawKb": 3.56,
    "gzipKb": 1.44,
    "treeShakable": true,
    "ssr": false
  },
  {
    "slug": "page",
    "rawKb": 167.66,
    "gzipKb": 36.18,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "page-layout",
    "rawKb": 5.3,
    "gzipKb": 1.49,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "quote",
    "rawKb": 6.21,
    "gzipKb": 1.91,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "radio",
    "rawKb": 3.57,
    "gzipKb": 1.16,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "radio-card",
    "rawKb": 9.15,
    "gzipKb": 2.6,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "reset",
    "rawKb": 2.63,
    "gzipKb": 0.94,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "scroll-area",
    "rawKb": 13.96,
    "gzipKb": 3.54,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "separator",
    "rawKb": 1.06,
    "gzipKb": 0.48,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "server-query",
    "rawKb": 20.61,
    "gzipKb": 5.49,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "side-nav",
    "rawKb": 26.63,
    "gzipKb": 6.04,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "skeleton",
    "rawKb": 3.18,
    "gzipKb": 1.08,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "switch",
    "rawKb": 1.46,
    "gzipKb": 0.66,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "table",
    "rawKb": 3.86,
    "gzipKb": 1.09,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "tabs",
    "rawKb": 12.65,
    "gzipKb": 3.39,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "timeline",
    "rawKb": 18.27,
    "gzipKb": 4.5,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "toast",
    "rawKb": 23.28,
    "gzipKb": 6.2,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "tooltip",
    "rawKb": 8.28,
    "gzipKb": 2.23,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "typography",
    "rawKb": 3.46,
    "gzipKb": 0.98,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "virtual-list",
    "rawKb": 2.61,
    "gzipKb": 1.02,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "visible",
    "rawKb": 2.15,
    "gzipKb": 0.84,
    "treeShakable": true,
    "ssr": true
  },
  {
    "slug": "widget",
    "rawKb": 16.49,
    "gzipKb": 4.65,
    "treeShakable": true,
    "ssr": true
  }
];

export function getComponentPerformance(slug: string): ComponentPerformanceMetric | undefined {
  return componentPerformanceMetrics.find((metric) => metric.slug === slug);
}
